### ISSUE TITLE
Consider adding a license and info for new contributors?

### ISSUE THREAD

**Issue by inputsh** [mehcode/awesome-atom#2]
I think that your list misses two things:
1. An appropriate license for your work. Your list is currently unlicensed.
2. A file called `CONTRIBUTE.md` where new contributors can find a way to contribute to this list, which formatting rules should we follow and things like that.

**Comment by mehcode** [comment]
1. Done on license 
2. The file is normally called `CONTRIBUTING.md`. Feel free to make and add one. https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md seems like a good place to look at.
