### ISSUE TITLE
Consider linking back to sindresorhus/awesome

### ISSUE THREAD

**Issue by inputsh** [mehcode/awesome-atom#3]
GitHub user @sindresorhus made an excellent list that combines awesome lists hosted on GitHub. You can find it here: https://github.com/sindresorhus/awesome

I took the liberty of including your list to the list of editors a day or two ago. By doing so, this repo will surely get more viewers.

I think that it would be appropriate for you to link back to this list to show your readers where they can get even more awesomenesses on various topics.

I decided to create an issue about this before I submit my Pull Request to get your approval or disapproval for my Pull Request. After all, you are the creator of this list and your opinion on this is crucial.

**Comment by mehcode** [comment]
:100: 

Go right ahead sir. 

> I took the liberty of including your list to the list of editors a day or two ago. By doing so, this repo will surely get more viewers.

Even more awesome.

---

:door: :open_hands: Commit access is yours.

**Comment by inputsh** [comment]
Thank you! :smile:
